name: Run Vitest tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install test tools
        run: npm install -D vitest jsdom

      - name: Install vue test tools
        run: npm install -D @vitejs/plugin-vue @vue/test-utils

      - name: Run tests with Vitest
        run: npm test
